BEGIN;
SELECT setval(pg_get_serial_sequence('"projects_master"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_master";
SELECT setval(pg_get_serial_sequence('"projects_type"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_type";
SELECT setval(pg_get_serial_sequence('"projects_theme_fonts"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_theme_fonts";
SELECT setval(pg_get_serial_sequence('"projects_theme_color_combinations"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_theme_color_combinations";
SELECT setval(pg_get_serial_sequence('"projects_theme"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_theme";
SELECT setval(pg_get_serial_sequence('"projects_publication_available_blocks"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_publication_available_blocks";
SELECT setval(pg_get_serial_sequence('"projects_publication"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_publication";
SELECT setval(pg_get_serial_sequence('"projects_block"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_block";
SELECT setval(pg_get_serial_sequence('"projects_preset"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_preset";
SELECT setval(pg_get_serial_sequence('"projects_presetitem"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_presetitem";
SELECT setval(pg_get_serial_sequence('"projects_article"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_article";
SELECT setval(pg_get_serial_sequence('"projects_codeblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_codeblock";
SELECT setval(pg_get_serial_sequence('"projects_colorsblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_colorsblock";
SELECT setval(pg_get_serial_sequence('"projects_coverblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_coverblock";
SELECT setval(pg_get_serial_sequence('"projects_headingblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_headingblock";
SELECT setval(pg_get_serial_sequence('"projects_imageassetblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_imageassetblock";
SELECT setval(pg_get_serial_sequence('"projects_listblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_listblock";
SELECT setval(pg_get_serial_sequence('"projects_photoblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_photoblock";
SELECT setval(pg_get_serial_sequence('"projects_photo"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_photo";
SELECT setval(pg_get_serial_sequence('"projects_photosblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_photosblock";
SELECT setval(pg_get_serial_sequence('"projects_pullquoteblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_pullquoteblock";
SELECT setval(pg_get_serial_sequence('"projects_textblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_textblock";
SELECT setval(pg_get_serial_sequence('"projects_videoblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_videoblock";
SELECT setval(pg_get_serial_sequence('"projects_audioblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_audioblock";
SELECT setval(pg_get_serial_sequence('"projects_fontsblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_fontsblock";
SELECT setval(pg_get_serial_sequence('"projects_purchaseblock"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_purchaseblock";
SELECT setval(pg_get_serial_sequence('"projects_color"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_color";
SELECT setval(pg_get_serial_sequence('"projects_imageasset"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_imageasset";
SELECT setval(pg_get_serial_sequence('"projects_colorcombination"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_colorcombination";
SELECT setval(pg_get_serial_sequence('"projects_purchaselink"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "projects_purchaselink";

COMMIT;
